import { randomUUID } from 'node:crypto'
import { Router } from 'express'
import { canEditScope, isPlanCreator, requireMembership } from '../access.js'
import { requireUser } from '../auth.js'
import { db } from '../db.js'
import { fail } from '../errors.js'
import expensesRouter from './expenses.js'

const KINDS = ['expense', 'saving']
const TAX_TIMINGS = ['monthly', 'yearly']

const router = Router()

router.use(requireUser)

const listPlans = db.prepare(`
  select p.id, p.name, p.created_by
  from plans p join plan_members m on m.plan_id = p.id
  where m.user_id = ? order by p.created_at
`)
const insertPlan = db.prepare('insert into plans (id, name, created_by, created_at) values (?, ?, ?, ?)')
const insertMember = db.prepare('insert or ignore into plan_members (plan_id, user_id, joined_at) values (?, ?, ?)')
const findPlan = db.prepare('select id, name, created_by, tax_timing from plans where id = ?')
const listMembers = db.prepare(`
  select m.user_id, m.net_monthly, m.annual_tax, u.display_name
  from plan_members m join users u on u.id = m.user_id
  where m.plan_id = ? order by m.joined_at
`)
const listGroups = db.prepare('select * from plan_groups where plan_id = ? order by position')
const listLines = db.prepare('select * from plan_lines where plan_id = ? order by position')
const findUserByEmail = db.prepare('select id from users where email = ?')
const findGroup = db.prepare('select * from plan_groups where id = ?')
const findLine = db.prepare('select * from plan_lines where id = ?')
const updateTaxTiming = db.prepare('update plans set tax_timing = ? where id = ?')
const updateFigures = db.prepare('update plan_members set net_monthly = ?, annual_tax = ? where plan_id = ? and user_id = ?')
const insertGroup = db.prepare(
  'insert into plan_groups (id, plan_id, kind, label, color, owner_id, position) values (@id, @plan_id, @kind, @label, @color, @owner_id, @position)'
)
const updateGroup = db.prepare(
  'update plan_groups set label = @label, color = @color, owner_id = @owner_id, position = @position where id = @id and plan_id = @plan_id'
)
const insertLine = db.prepare(
  'insert into plan_lines (id, plan_id, kind, label, amount, owner_id, group_id, position) values (@id, @plan_id, @kind, @label, @amount, @owner_id, @group_id, @position)'
)
const updateLine = db.prepare(
  'update plan_lines set label = @label, amount = @amount, owner_id = @owner_id, group_id = @group_id, position = @position where id = @id and plan_id = @plan_id'
)
const deleteGroup = db.prepare('delete from plan_groups where id = ? and plan_id = ?')
const deleteLine = db.prepare('delete from plan_lines where id = ? and plan_id = ?')

/**
 * Identifier generated by the browser, as the database used to do
 * @param {unknown} value
 */
function readId(value) {
  const id = String(value ?? '')

  if (!id || id.length > 64) {
    fail(400, 'Identifiant invalide.')
  }

  return id
}

/**
 * @param {unknown} value
 */
function readKind(value) {
  if (!KINDS.includes(value)) {
    fail(400, 'Type de ligne inconnu.')
  }

  return value
}

/**
 * @param {unknown} value
 */
function readAmount(value) {
  const amount = Number(value)

  if (!Number.isFinite(amount)) {
    fail(400, 'Montant invalide.')
  }

  return amount
}

/**
 * @param {unknown} value
 */
function readPosition(value) {
  const position = Number(value)

  if (!Number.isInteger(position)) {
    return 0
  }

  return position
}

/**
 * Scope sent by the client, refused when it is neither the common part nor the person themselves
 * @param {string} planId
 * @param {string} userId
 * @param {unknown} value
 */
function readOwner(planId, userId, value) {
  const ownerId = value ?? null

  if (!canEditScope(planId, userId, ownerId)) {
    fail(403, 'Vous ne pouvez modifier que la partie commune et votre propre partie.')
  }

  return ownerId
}

/**
 * Imported rows may only belong to the common part or to a member of the plan
 * @param {Set<string>} memberIds
 * @param {unknown} value
 */
function readImportedOwner(memberIds, value) {
  const ownerId = value ?? null

  if (!!ownerId && !memberIds.has(ownerId)) {
    fail(400, 'Les lignes importées doivent appartenir à des membres du plan.')
  }

  return ownerId
}

/**
 * Refuses to touch a row that belongs to another member
 * @param {string} planId
 * @param {string} userId
 * @param {object} [row]
 */
function requireEditable(planId, userId, row) {
  if (!row || row.plan_id !== planId) {
    fail(404, 'Cette ligne n’existe plus.')
  }

  readOwner(planId, userId, row.owner_id)
}

/**
 * Placement columns of a line: inside a sub-group it always shares the sub-group's scope
 * @param {string} planId
 * @param {string} kind
 * @param {unknown} groupId
 * @param {string | null} ownerId
 */
function resolvePlacement(planId, kind, groupId, ownerId) {
  if (!groupId) {
    return { group_id: null, owner_id: ownerId }
  }

  const group = findGroup.get(String(groupId))

  if (!group || group.plan_id !== planId || group.kind !== kind) {
    fail(400, 'Ce sous-groupe n’appartient pas à cette section du plan.')
  }

  return { group_id: group.id, owner_id: group.owner_id }
}

/**
 * Row of a sub-group, rebuilt from the request rather than trusted as sent
 * @param {object} req
 */
function toGroupRow(req) {
  const planId = req.params.planId

  return {
    id: readId(req.body.id),
    plan_id: planId,
    kind: readKind(req.body.kind),
    label: String(req.body.label ?? ''),
    color: String(req.body.color ?? '1'),
    owner_id: readOwner(planId, req.userId, req.body.owner_id),
    position: readPosition(req.body.position),
  }
}

/**
 * Row of a line, rebuilt from the request rather than trusted as sent
 * @param {object} req
 */
function toLineRow(req) {
  const planId = req.params.planId
  const kind = readKind(req.body.kind)
  const owner = readOwner(planId, req.userId, req.body.owner_id)

  return {
    id: readId(req.body.id),
    plan_id: planId,
    kind,
    label: String(req.body.label ?? ''),
    amount: readAmount(req.body.amount),
    position: readPosition(req.body.position),
    ...resolvePlacement(planId, kind, req.body.group_id, owner),
  }
}

// A plan and its first member are created together
const createPlan = db.transaction((id, name, userId, now) => {
  insertPlan.run(id, name, userId, now)
  insertMember.run(id, userId, now)
})

// Appends a whole plan read from a JSON file, including the other members' parts
const importPlan = db.transaction((planId, payload, memberIds) => {
  payload.groups.forEach((group, index) => {
    insertGroup.run({
      id: readId(group.id),
      plan_id: planId,
      kind: readKind(group.kind),
      label: String(group.label ?? ''),
      color: String(group.color ?? '1'),
      owner_id: readImportedOwner(memberIds, group.owner_id),
      position: readPosition(group.position ?? index),
    })
  })

  payload.lines.forEach((line, index) => {
    const kind = readKind(line.kind)
    const owner = readImportedOwner(memberIds, line.owner_id)

    insertLine.run({
      id: readId(line.id),
      plan_id: planId,
      kind,
      label: String(line.label ?? ''),
      amount: readAmount(line.amount),
      position: readPosition(line.position ?? index),
      ...resolvePlacement(planId, kind, line.group_id, owner),
    })
  })

  payload.members.forEach((member) => {
    const memberId = readImportedOwner(memberIds, member.user_id)

    updateFigures.run(readAmount(member.net_monthly), readAmount(member.annual_tax), planId, memberId)
  })

  if (TAX_TIMINGS.includes(payload.tax_timing)) {
    updateTaxTiming.run(payload.tax_timing, planId)
  }
})

// Plans the person belongs to
router.get('/', (req, res) => {
  res.json(listPlans.all(req.userId))
})

router.post('/', (req, res) => {
  const name = String(req.body.name ?? '').trim()

  if (!name) {
    fail(400, 'Le nom du plan est obligatoire.')
  }

  const id = randomUUID()

  createPlan(id, name, req.userId, new Date().toISOString())
  res.json({ id })
})

// Everything below concerns one plan, readable by its members only
router.use('/:planId', requireMembership)

router.get('/:planId', (req, res) => {
  const { planId } = req.params

  res.json({
    plan: findPlan.get(planId),
    members: listMembers.all(planId),
    groups: listGroups.all(planId),
    lines: listLines.all(planId),
  })
})

// Only the shared settings, the rest of the plan row is never rewritten by clients
router.patch('/:planId', (req, res) => {
  const taxTiming = String(req.body.tax_timing ?? '')

  if (!TAX_TIMINGS.includes(taxTiming)) {
    fail(400, 'Réglage inconnu.')
  }

  updateTaxTiming.run(taxTiming, req.params.planId)
  res.json({})
})

// Only the creator adds members, by the email of an existing account
router.post('/:planId/members', (req, res) => {
  const { planId } = req.params
  const email = String(req.body.email ?? '').trim().toLowerCase()

  if (!isPlanCreator(planId, req.userId)) {
    fail(403, 'Seul le créateur du plan peut ajouter des membres.')
  }

  const member = findUserByEmail.get(email)

  if (!member) {
    fail(404, 'Aucun compte ne correspond à cette adresse.')
  }

  insertMember.run(planId, member.id, new Date().toISOString())
  res.json({})
})

// A member only ever edits their own income and tax
router.patch('/:planId/members/me', (req, res) => {
  updateFigures.run(readAmount(req.body.net_monthly), readAmount(req.body.annual_tax), req.params.planId, req.userId)
  res.json({})
})

router.post('/:planId/groups', (req, res) => {
  insertGroup.run(toGroupRow(req))
  res.json({})
})

router.put('/:planId/groups/:id', (req, res) => {
  requireEditable(req.params.planId, req.userId, findGroup.get(req.params.id))
  updateGroup.run(toGroupRow(req))
  res.json({})
})

// Its lines move up to the scope it belonged to, the foreign key clearing their group
router.delete('/:planId/groups/:id', (req, res) => {
  requireEditable(req.params.planId, req.userId, findGroup.get(req.params.id))
  deleteGroup.run(req.params.id, req.params.planId)
  res.json({})
})

router.post('/:planId/lines', (req, res) => {
  insertLine.run(toLineRow(req))
  res.json({})
})

router.put('/:planId/lines/:id', (req, res) => {
  requireEditable(req.params.planId, req.userId, findLine.get(req.params.id))
  updateLine.run(toLineRow(req))
  res.json({})
})

router.delete('/:planId/lines/:id', (req, res) => {
  requireEditable(req.params.planId, req.userId, findLine.get(req.params.id))
  deleteLine.run(req.params.id, req.params.planId)
  res.json({})
})

router.post('/:planId/import', (req, res) => {
  const { planId } = req.params

  if (!isPlanCreator(planId, req.userId)) {
    fail(403, 'Seul le créateur du plan peut importer.')
  }

  const memberIds = new Set(listMembers.all(planId).map((member) => member.user_id))

  importPlan(planId, req.body, memberIds)
  res.json({})
})

router.use('/:planId/expenses', expensesRouter)

export default router
