import { fail } from './errors.js'

// Shared readers for values coming from the browser, refused rather than coerced silently

const KINDS = ['expense', 'saving']

/**
 * Identifier generated by the browser, as the database used to do
 * @param {unknown} value
 */
export function readId(value) {
  const id = String(value ?? '')

  if (!id || id.length > 64) {
    fail(400, 'Identifiant invalide.')
  }

  return id
}

/**
 * @param {unknown} value
 */
export function readKind(value) {
  if (!KINDS.includes(value)) {
    fail(400, 'Type de ligne inconnu.')
  }

  return value
}

/**
 * @param {unknown} value
 */
export function readAmount(value) {
  const amount = Number(value)

  if (!Number.isFinite(amount)) {
    fail(400, 'Montant invalide.')
  }

  return amount
}

/**
 * Yes/no flag stored as 0 or 1, anything but true meaning no
 * @param {unknown} value
 */
export function readFlag(value) {
  if (value === true || value === 1) {
    return 1
  }

  return 0
}

/**
 * @param {unknown} value
 */
export function readPosition(value) {
  const position = Number(value)

  if (!Number.isInteger(position)) {
    return 0
  }

  return position
}
